title = "CNCF Branding"
disableKinds = ["section", "taxonomy", "taxonomyTerm"]
baseURL = "https://cncf-branding.netlify.com"

[params]
description = "Colors and logos for every CNCF project"
fontAwesomeVersion = "5.3.1"
sansSerifFont = "Lato"
twitterhandle = "CloudNativeFdn"

[[params.fonts]]
name = "Lato"
sizes = [300, 400, 600, 700]

[mediaTypes."text/netlify"]
delimiter = ""

[outputFormats.REDIRECTS]
mediaType = "text/netlify"
baseName = "_redirects"

[outputs]
home = ["HTML", "REDIRECTS"]
