title = "CNCF Branding"
disableKinds = ["section", "taxonomy", "taxonomyTerm"]

[params]
description = "Colors and logos for every CNCF project"
fontAwesomeVersion = "5.3.1"
sansSerifFont = "Open Sans"

[[params.fonts]]
name = "Open Sans"
sizes = [300, 400, 600, 700]
