title = "CNCF Branding"
disableKinds = ["section", "taxonomy", "taxonomyTerm"]
baseURL = "https://cncf-branding.netlify.com"

[params]
description = "Colors and logos for the Cloud Native Computing Foundation and its open source projects"
fontAwesomeVersion = "5.3.1"
twitterhandle = "CloudNativeFdn"

[params.logos]
navbar = "img/other/cncf/horizontal/color/cncf-color.png"

[[params.fonts]]
name = "Open Sans"
sizes = [300, 400, 600, 700]

[mediaTypes."text/netlify"]
delimiter = ""

[outputFormats.REDIRECTS]
mediaType = "text/netlify"
baseName = "_redirects"

[outputs]
home = ["HTML", "REDIRECTS"]
